[[redirects]]
  from = "https://attrace.network/solution/referral-network/"
  to = "https://attrace.com/about/referral-farming/"
  status = 301
  force = true

[[redirects]]
  from = "https://attrace.network/solution/foundation/"
  to = "https://attrace.com/about/"
  status = 301
  force = true

[[redirects]]
  from = "https://attrace.network/solution/referral-conversion-token/"
  to = "https://attrace.com/about/referral-farming/"
  status = 301
  force = true

[[redirects]]
  from = "https://attrace.network/solution/verifier-nodes/"
  to = "https://attrace.com/about/oracles"
  status = 301
  force = true

[[redirects]]
  from = "https://attrace.network/ecosystem/"
  to = "https://attrace.com/about/tokenomics"
  status = 301
  force = true

[[redirects]]
  from = "https://attrace.network/community/attr-token/"
  to = "https://attrace.com/about/attrace-token"
  status = 301
  force = true

[[redirects]]
  from = "https://attrace.network/community/mission/"
  to = "https://attrace.com/about/"
  status = 301
  force = true

[[redirects]]
  from = "https://attrace.network/community/mission/"
  to = "https://attrace.com/about/"
  status = 301
  force = true

[[redirects]]
  from = "https://attrace.network"
  to = "https://attrace.com"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.attrace.network"
  to = "https://attrace.com"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.attrace.network/*"
  to = "https://attrace.com"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.classic.attrace.network"
  to = "https://attrace.com"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.classic.attrace.network/*"
  to = "https://attrace.com"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.attrace.com"
  to = "https://attrace.com"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.attrace.com/*"
  to = "https://attrace.com"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.classic.attrace.com"
  to = "https://attrace.com"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.classic.attrace.com/*"
  to = "https://attrace.com"
  status = 301
  force = true

[[redirects]]
  from = "https://attrace.network/*"
  to = "https://attrace.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/solution/referral-network/"
  to = "/about/referral-farming/"
  status = 301

[[redirects]]
  from = "/solution/foundation/"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/solution/referral-conversion-token/"
  to = "/about/referral-farming/"
  status = 301

[[redirects]]
  from = "/solution/verifier-nodes/"
  to = "/about/oracles"
  status = 301

[[redirects]]
  from = "/ecosystem/"
  to = "/about/tokenomics"
  status = 301

[[redirects]]
  from = "/community/attr-token/"
  to = "/about/attrace-token"
  status = 301

[[redirects]]
  from = "/community/mission/"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/community/mission/"
  to = "/about/"
  status = 301

[[redirects]]
  from = "https://www.attrace.network"
  to = "https://attrace.com"
  status = 301
  force = true

[[redirects]]
  from = "https://www.attrace.network/*"
  to = "https://attrace.com/"
  status = 301
  force = true


[[redirects]]
  from = "https://attrace.net"
  to = "https://attrace.com"
  status = 301
  force = true

[[redirects]]
  from = "https://attrace.net/*"
  to = "https://attrace.com/"
  status = 301
  force = true

[[redirects]]
  from = "https://www.attrace.net"
  to = "https://attrace.com"
  status = 301
  force = true

[[redirects]]
  from = "https://www.attrace.net/*"
  to = "https://attrace.com/"
  status = 301
  force = true

[[redirects]]
  from = "https://attr.link"
  to = "https://attrace.com"
  status = 301
  force = true

[[redirects]]
  from = "https://attr.link/*"
  to = "https://attrace.com/"
  status = 301
  force = true

[[redirects]]
  from = "https://www.attr.link"
  to = "https://attrace.com"
  status = 301
  force = true

[[redirects]]
  from = "https://www.attr.link/*"
  to = "https://attrace.com/"
  status = 301
  force = true

[[redirects]]
  from = "https://attrace.org"
  to = "https://attrace.com"
  status = 301
  force = true

[[redirects]]
  from = "https://attrace.org/*"
  to = "https://attrace.com/"
  status = 301
  force = true

[[redirects]]
  from = "https://www.attrace.org"
  to = "https://attrace.com"
  status = 301
  force = true

[[redirects]]
  from = "https://www.attrace.org/*"
  to = "https://attrace.com/"
  status = 301
  force = true

[[redirects]]
  from = "https://attrace.express"
  to = "https://attrace.com"
  status = 301
  force = true

[[redirects]]
  from = "https://attrace.express/*"
  to = "https://attrace.com/"
  status = 301
  force = true

[[redirects]]
  from = "https://www.attrace.express"
  to = "https://attrace.com"
  status = 301
  force = true

[[redirects]]
  from = "https://www.attrace.express/*"
  to = "https://attrace.com/"
  status = 301
  force = true

[[redirects]]
  from = "https://affpay.io"
  to = "https://attrace.com"
  status = 301
  force = true

[[redirects]]
  from = "/blog"
  to = "https://blog.attrace.com"
  status = 200
  force = true
  
[[redirects]]
  from = "/_next/*"
  to = "https://blog.attrace.com/_next/*"
  status = 200
  force = true

[[redirects]]
  from = "/tags/*"
  to = "https://blog.attrace.com/tags/:splat"
  status = 200
  force = true  

[[redirects]]
  from = "/authors/*"
  to = "https://blog.attrace.com/authors/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/marketing/*"
  to = "https://blog.attrace.com/marketing/:splat"
  status = 200
  force = true  
  
[[redirects]]
  from = "/test-category/*"
  to = "https://blog.attrace.com/test-category/:splat"
  status = 200
  force = true
